=== longclotilde00-del/first-assignment---encoding-project/DTDFILE1.dtd
<!ELEMENT TEI (teiHeader, correspDesc+, text)>
<!ATTLIST TEI xmlns CDATA #IMPLIED>

<!ELEMENT teiHeader (fileDesc)>

<!ELEMENT fileDesc (titleStmt, respStmt, publicationStmt, sourceDesc)>
<!ELEMENT titleStmt (title, author)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT respStmt (resp, name)>
<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT publicationStmt (distributor?)>
<!ELEMENT distributor (#PCDATA)>
<!ELEMENT sourceDesc (biblStruct)>
<!ELEMENT biblStruct (monogr)>
<!ELEMENT monogr (editor, title, imprint)>
<!ELEMENT editor (#PCDATA)>
<!ELEMENT imprint (pubPlace?, publisher, date)>
<!ELEMENT pubPlace (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date when CDATA #IMPLIED>
<!ELEMENT encodingDesc (samplingDecl)>
<!ELEMENT samplingDecl (#PCDATA)>
<!ELEMENT profileDesc (creation, langUsage)>
<!ELEMENT creation (date)>
<!ELEMENT langUsage (language)>
<!ELEMENT language (#PCDATA)>

<!ELEMENT correspDesc (correspAction+)>
<!ATTLIST correspDesc xml:id ID #IMPLIED>
<!ELEMENT correspAction (persName?, placeName?, date)>
<!ATTLIST correspAction type (sent | received) #REQUIRED>
<!ELEMENT persName (#PCDATA)>
<!ELEMENT placeName (#PCDATA)>

<!ELEMENT text (body)>
<!ELEMENT body (div)>
<!ELEMENT div (head?, opener?, p+, closer?)>
<!ATTLIST div type (letter) #REQUIRED>
<!ELEMENT head (#PCDATA)>
<!ELEMENT opener (dateline)>
<!ELEMENT dateline (placeName?, date)>
<!ELEMENT placename (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT closer (salute?, signed?)>
<!ELEMENT salute (#PCDATA)>
<!ELEMENT signed (#PCDATA)>
<!ELEMENT postscript (label?, p+)>
<!ELEMENT label (#PCDATA)>

=== longclotilde00-del/first-assignment---encoding-project/corresp.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng"?>
 
<!DOCTYPE TEI SYSTEM "DTDFILE1.dtd">

<TEI xmlns="http://www.tei-c.org/ns/1.0">

  <teiHeader>
      <fileDesc>
         <titleStmt>
            <title></title>
            <author></author>
            <respStmt>
               <resp></resp>
               <name></name>
            </respStmt>
         </titleStmt>
         <publicationStmt>
              <distributor></distributor>
         </publicationStmt>
         <sourceDesc>
             <biblStruct>
               <monogr>
                  <editor></editor>
                  <title></title>
                  <imprint>
                     <pubPlace></pubPlace>
                     <publisher></publisher>
                     <date></date>
                  </imprint>
               </monogr>
            </biblStruct>
         </sourceDesc>
      </fileDesc>
      <encodingDesc>
         <samplingDecl>
            <p></p>
         </samplingDecl>
      </encodingDesc>
       <profileDesc>
         <creation>
            <date></date>
         </creation>
         <langUsage>
            <language ident="fr">fran√ßais</language>
         </langUsage>
      <correspDesc xml:id="message1">
         <correspAction type="sent">
            <persName></persName>
            <placeName></placeName>
            <date/>
         </correspAction>
      </correspDesc>
       </profileDesc>      
  </teiHeader>
  
  <text>
     <body>
      <div type= "letter">
        <head></head> 
        <opener>
            <dateline>
               <placeName></placeName>
               <date></date>
            </dateline>
        </opener>
            <p></p>
        <closer>
            <salute></salute>
            <signed></signed>
        </closer>
        <postscript>
           <label></label>
           <p></p>
        </postscript>
      </div>
     </body>
  </text>
</TEI>
